version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true
image: Ubuntu2004
install:
- sh: >-
    sudo dpkg --add-architecture i386

    sudo apt update

    dpkg-checkbuilddeps 2>&1 | sed 's/dpkg-checkbuilddeps:\serror:\sUnmet build dependencies: //g' | sed 's/[\(][^)]*[\)] //g' | sed 's/|//g' | xargs -n 1 sudo apt install -y

    sudo apt install --yes qt5-default g++-multilib libc6-dev-i386 libx11-6:i386 libx11-dev:i386 libx11-xcb1:i386 libx11-xcb-dev:i386 libxcb-randr0-dev:i386 libasound2:i386 libasound2-dev:i386 libavutil56:i386 libavutil-dev:i386 libswresample3:i386 libswresample-dev:i386 libfreetype6:i386 libfreetype6-dev:i386 libfontconfig1:i386 libfontconfig1-dev:i386
build_script:
- sh: sudo dpkg-buildpackage -us -uc -b
after_build:
- sh: sudo mv ../libtas*deb ./
- sh: for f in libtas*deb; do mv $f ${f/_amd/_${APPVEYOR_REPO_COMMIT:0:7}_amd}; done;
artifacts:
- path: libtas*.deb
  name: libtas

- path: libtas-dbgsym*.ddeb
  name: libtas-dbgsym
